# Generated by Django 4.2 on 2023-04-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinted', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='vinted_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='historicalbrand',
            name='vinted_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='vinted_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='vinted_id',
            field=models.IntegerField(unique=True),
        ),
    ]
