# Generated by Django 4.2 on 2023-04-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinted', '0002_alter_brand_vinted_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='items_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalbrand',
            name='items_amount',
            field=models.IntegerField(null=True),
        ),
    ]
